project:
  type: website
  output-dir: docs

website:
  title: "Vaasuki Marupaka"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer: 
    center: "Copyright 2023, Vaasuki Marupaka" 
  

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

